version: '3'

services:
  angular:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ".:/projects"
    command: 
      sh -c 'cd angular-app ; ng serve --host 0.0.0.0'
    tty: true

  strapi:
    image: node:18
    working_dir: /usr/src/app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/usr/src/app
    entrypoint:
      - sh
    command:
      - -c
      - |
        yarn install
        yarn develop
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d